@0xf2ef8dbffc81d113;  # unique file ID, generated by `capnp id`

struct LogEntry {
  timestamp @0 :Int64;
  bno055 @1 :BNO055;

  struct BNO055 {
    direction @0 :DirectionalVector;
  }
}

struct DirectionalVector {
  x @0 :Int64;
  y @1 :Int64;
  z @2 :Int64;
}
