/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: models/telemetry.proto */

#ifndef PROTOBUF_C_models_2ftelemetry_2eproto__INCLUDED
#define PROTOBUF_C_models_2ftelemetry_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Telemetry Telemetry;


/* --- enums --- */


/* --- messages --- */

struct  _Telemetry
{
  ProtobufCMessage base;
  int64_t timestampstart;
  double x;
  double y;
  double z;
};
#define TELEMETRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&telemetry__descriptor) \
    , 0, 0, 0, 0 }


/* Telemetry methods */
void   telemetry__init
                     (Telemetry         *message);
size_t telemetry__get_packed_size
                     (const Telemetry   *message);
size_t telemetry__pack
                     (const Telemetry   *message,
                      uint8_t             *out);
size_t telemetry__pack_to_buffer
                     (const Telemetry   *message,
                      ProtobufCBuffer     *buffer);
Telemetry *
       telemetry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   telemetry__free_unpacked
                     (Telemetry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Telemetry_Closure)
                 (const Telemetry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor telemetry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_models_2ftelemetry_2eproto__INCLUDED */
