/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: telemetry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "telemetry.pb-c.h"
void   telemetry__init
                     (Telemetry         *message)
{
  static const Telemetry init_value = TELEMETRY__INIT;
  *message = init_value;
}
size_t telemetry__get_packed_size
                     (const Telemetry *message)
{
  assert(message->base.descriptor == &telemetry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t telemetry__pack
                     (const Telemetry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &telemetry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t telemetry__pack_to_buffer
                     (const Telemetry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &telemetry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Telemetry *
       telemetry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Telemetry *)
     protobuf_c_message_unpack (&telemetry__descriptor,
                                allocator, len, data);
}
void   telemetry__free_unpacked
                     (Telemetry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &telemetry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor telemetry__field_descriptors[4] =
{
  {
    "timestampStart",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Telemetry, timestampstart),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Telemetry, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Telemetry, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Telemetry, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned telemetry__field_indices_by_name[] = {
  0,   /* field[0] = timestampStart */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange telemetry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor telemetry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Telemetry",
  "Telemetry",
  "Telemetry",
  "",
  sizeof(Telemetry),
  4,
  telemetry__field_descriptors,
  telemetry__field_indices_by_name,
  1,  telemetry__number_ranges,
  (ProtobufCMessageInit) telemetry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
