/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: logs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "logs.pb-c.h"
void   logs__log_entry__init
                     (Logs__LogEntry         *message)
{
  static const Logs__LogEntry init_value = LOGS__LOG_ENTRY__INIT;
  *message = init_value;
}
void   logs__init
                     (Logs         *message)
{
  static const Logs init_value = LOGS__INIT;
  *message = init_value;
}
size_t logs__get_packed_size
                     (const Logs *message)
{
  assert(message->base.descriptor == &logs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logs__pack
                     (const Logs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logs__pack_to_buffer
                     (const Logs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Logs *
       logs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Logs *)
     protobuf_c_message_unpack (&logs__descriptor,
                                allocator, len, data);
}
void   logs__free_unpacked
                     (Logs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor logs__log_entry__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Logs__LogEntry, timestamp),
    &google__protobuf__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bno055",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Logs__LogEntry, bno055),
    &bno055__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logs__log_entry__field_indices_by_name[] = {
  1,   /* field[1] = bno055 */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange logs__log_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor logs__log_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Logs.LogEntry",
  "LogEntry",
  "Logs__LogEntry",
  "",
  sizeof(Logs__LogEntry),
  2,
  logs__log_entry__field_descriptors,
  logs__log_entry__field_indices_by_name,
  1,  logs__log_entry__number_ranges,
  (ProtobufCMessageInit) logs__log_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logs__field_descriptors[1] =
{
  {
    "log",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Logs, n_log),
    offsetof(Logs, log),
    &logs__log_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logs__field_indices_by_name[] = {
  0,   /* field[0] = log */
};
static const ProtobufCIntRange logs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Logs",
  "Logs",
  "Logs",
  "",
  sizeof(Logs),
  1,
  logs__field_descriptors,
  logs__field_indices_by_name,
  1,  logs__number_ranges,
  (ProtobufCMessageInit) logs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
